# Generated by Django 3.2.7 on 2021-11-01 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('brand', models.CharField(max_length=25, null=True)),
                ('code', models.CharField(max_length=40)),
                ('deal_price', models.FloatField(null=True)),
                ('seller', models.CharField(max_length=255)),
                ('main_price', models.FloatField(null=True)),
                ('stars', models.FloatField(null=True)),
                ('count', models.IntegerField(null=True)),
                ('main_image', models.CharField(max_length=1000)),
                ('create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.product')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.product')),
            ],
        ),
    ]
