# Generated by Django 3.2.7 on 2021-10-27 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_product_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='main_image',
        ),
    ]
